export enum PLATFORM_FEATURES {
    GET_ITEMS = 7,
    ADD_UPTATE_ITEM = 8,
    ADJUST_ITEM = 9,
    GET_PARTIES = 10,
    ADD_UPDATE_PARTY = 11,
    GET_PURCHASES = 12,
    ADD_UPDATE_PURCHASE = 13,
    GET_SALES = 14,
    ADD_UPDATE_SALE = 15,
    GET_QUOTATIONS = 16,
    ADD_UPDATE_QUOTATION = 17,
    GET_CASHFLOW_SUMMARY = 18
}