export enum PLATFORM_FEATURES {
    GET_ITEMS = 7,
    ADD_UPTATE_ITEM = 8,
    ADJUST_ITEM = 9,
    GET_PARTIES = 10,
    ADD_UPDATE_PARTY = 11,
    GET_PURCHASES = 12,
    ADD_UPDATE_PURCHASE = 13
}