export enum ReactQueryKeys {
    allCountries = "allCountries",
    allCompanies = "allCompanies",
    company = "company",
    taxDetailsOfCountry = "taxDetailsOfCountry",
    userACLForCompany = "userACLForCompany",
    enabledPlatformFeatures = "enabledPlatformFeatures",
    items = "items",
    country = "country",
    units = "units",
    getItem = "getItem",
    parties = "parties",
    getParty = "getParty",
    purchases = "purchases",
    getPurchase = "getPurchase",
    sales = "sales",
    getSale = "getSale",
    quotations = "quotations",
    getQuotation = "getQuotation",
    cashFlowSummary = "cashFlowSummary",
    getTopSellersForCurrentMonth = "getTopSellersForCurrentMonth"
}
