export enum AppRoutes {
    login = "login",
    register = "register",
    viewAllCompanies = "view-all-companies",
    companySettings = "company-settings",
    addCompany = "add-company",
    dashboard = "dashboard",
    items = "items",
    addItem = "add-item",
    getItem = "get-item",
    getParty = "get-party",
    addParty = "add-party",
    getPurchase = "get-purchase",
    addPurchase = "add-purchase",
    addSale = "add-sale",
    getSale = "get-sale",
    addQuotation = "add-quotation",
    getQuotation = "get-quotation",
    getLowStockItems = "get-low-stock-items",
    roles = "roles",
    addRole = "add-role",
    getRole = "get-role",
    addUser = "add-user",
    getUser = "get-user",
    addBranch = "add-branch",
    addTransfer = "add-transfer",
    getTransfer = "get-transfer"
}